---

# rework this once https://github.com/ansible-collections/community.general/issues/8936 gets fixed
- name: ensure tasks run only on selected os releases
  block:

    - name: ensure tasks run only when key variables are defined
      block:
    
        - name: install wireguard tools
          ansible.builtin.package:
            name: wireguard-tools
            state: present
    
        - name: check if wireguard tunnel already exists
          ansible.builtin.shell:
            cmd: "touch {{ ansible_work_dir.path }}/$(nmcli connection show | grep {{ item.name }}) | cut -d ' ' -f 1"
          loop: "{{ wireguard }}"
          loop_control:
            label: "{{ item.name }}"
          changed_when: false
          no_log: "{{ hide_secrets }}"

        - name: upload wireguard configuration file
          ansible.builtin.template:
            src: templates/wg.conf.j2
            dest: "{{ ansible_work_dir.path }}/{{ item.device }}.conf"
          loop: "{{ wireguard }}"
          loop_control:
            label: "{{ item.name }}"
          when: wireguard_ip[item.name] is defined
          no_log: "{{ hide_secrets }}"

        - name: import wireguard configuration file
          ansible.builtin.command:
            cmd: "nmcli connection import type wireguard file {{ item.device }}.conf"
            chdir: "{{ ansible_work_dir.path }}"
            creates: "{{ item.name }}"
          loop: "{{ wireguard }}"
          loop_control:
            label: "{{ item.name }}"
          when: wireguard_ip[item.name] is defined
          no_log: "{{ hide_secrets }}"
    
        - name: configure wireguard interface(s)
          ansible.builtin.shell:
            cmd: "nmcli connection modify {{ item.device }} connection.id {{ item.name }}; nmcli connection modify {{ item.name }}  connection.autoconnect false; nmcli connection down {{ item.name }}"
            chdir: "{{ ansible_work_dir.path }}"
            creates: "{{ item.name }}"
          register: wg_config
          loop: "{{ wireguard }}"
          loop_control:
            label: "{{ item.name }}"
          when: wireguard_ip[item.name] is defined
          no_log: "{{ hide_secrets }}"


        - name: display wiregaurd configuration result
          ansible.builtin.debug:
            var: wg_config
            verbosity: 1
    
      when:
        - wireguard is defined
        - wireguard_key_private is defined
        - wireguard_key_public is defined

  when: >
    os_id.stdout == "bazzite" or
    os_id.stdout == "fedora" or
    os_id.stdout == "rhel" or
    os_id.stdout == "rocky" or
    os_id.stdout == "steamos"

...
