---

# rework this once https://github.com/ansible-collections/community.general/issues/8936 gets fixed
- name: ensure tasks run only on selected os releases
  block:

    - name: ensure tasks run only when key variables are defined
      block:
    
        - name: install wireguard tools
          ansible.builtin.package:
            name: wireguard-tools
            state: present
          when: ansible_distribution != "Bazzite"
    
        - name: check if wireguard tunnel already exists
          ansible.builtin.command:
            cmd: "nmcli connection show"
          changed_when: false
          register: nmcli_connections

        - name: display nmcli connections
          ansible.builtin.debug:
            var: nmcli_connections.stdout
            verbosity: 1

        - name: upload wireguard configuration file
          ansible.builtin.template:
            src: templates/wg.conf.j2
            dest: "{{ ansible_work_dir.path }}/{{ item.device }}.conf"
          loop: "{{ wireguard }}"
          loop_control:
            label: "{{ item.name }}"
          when: wireguard_ip[item.name] is defined
          no_log: "{{ hide_secrets }}"

        - name: import wireguard configuration file
          ansible.builtin.shell:
            cmd: "nmcli connection import type wireguard file {{ item.device }}.conf; nmcli connection down {{ item.device }}"
            chdir: "{{ ansible_work_dir.path }}"
          loop: "{{ wireguard }}"
          loop_control:
            label: "{{ item.name }}"
          when:
            - wireguard_ip[item.name] is defined
            - 'item.name not in nmcli_connections.stdout'
          timeout: 30
          no_log: "{{ hide_secrets }}"
    
        - name: configure wireguard interface(s)
          ansible.builtin.shell:
            cmd: "nmcli connection modify {{ item.device }} connection.id {{ item.name }}; nmcli connection modify {{ item.name }}  connection.autoconnect false"
            chdir: "{{ ansible_work_dir.path }}"
          register: wg_config
          loop: "{{ wireguard }}"
          loop_control:
            label: "{{ item.name }}"
          when:
            - wireguard_ip[item.name] is defined
            - 'item.name not in nmcli_connections.stdout'
          no_log: "{{ hide_secrets }}"


        - name: display wiregaurd configuration result
          ansible.builtin.debug:
            var: wg_config
            verbosity: 1
    
      when:
        - wireguard is defined
        - wireguard_key_private is defined
        - wireguard_key_public is defined

  when: >
    (ansible_distribution == "Archlinux" and ansible_distribution_release == "holo") or
    ansible_distribution == "Bazzite" or
    ansible_distribution == "Fedora" or
    ansible_distribution == "RedHat" or
    ansible_distribution == "Rocky"

...
